name: Deploy

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install deps
        run: sudo apt install -y pandoc trickle

      - name: Slow network to avoid rate limiting
        run: sudo tc qdisc add dev eth0 root tbf rate 1024kbit burst 32kbit

      - name: Build Site
        run: trickle -d 128 make

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
